[package]
name = "personal_diary"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4"
futures-util = "0.3.31"
rusqlite="0.32.1"
serde={version="1.0.214",features=["derive"]}
serde_json="1.0.132"
bcrypt = "0.15"
env_logger="0.11.5"
actix-files="0.6.6"

